services:
  ffc-doc-statement-receiver:
    build:
      context: .
      target: production
    image: ffc-doc-statement-receiver
    container_name: ffc-doc-statement-receiver
    depends_on:
      - ffc-doc-statement-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-doc-statement-receiver-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      REDIS_HOSTNAME: ffc-doc-statement-receiver-redis
      REDIS_PASSWORD: redis
      PORT: 3022

  ffc-doc-statement-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-doc-statement-azurite

  ffc-doc-statement-receiver-redis:
    image: redis:6.2.7
