{{- include "ffc-helm-library.container-secret" (list . "ffc-doc-statement-receiver.container-secret") -}}
{{- define "ffc-doc-statement-receiver.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  REDIS_PASSWORD: {{ quote .Values.container.redisPassword }}
{{- end -}}
