environment: production
environmentCode: dev
appInsights.connectionString: {\"uri\":\"https://devffcinfkv1001.vault.azure.net/secrets/devtest-ffcahwr-appInsights-connectionString\"}
container.messageQueueHost: DEVFFCINFSB1001.servicebus.windows.net
container.azureStorageAccountName: devffcdocst1001
container.redisHostname: DEVFFCINFRD1001.redis.cache.windows.net
container.redisPort: 6380
secretProviderClass.azure.keyvaultName: DEVFFCINFKV1001