environment: production
environmentCode: prd
appInsights.connectionString: InstrumentationKey=28a30887-2d2d-490f-8403-5bf1e75ae55f;IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/
container.messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
container.azureStorageAccountName: prdffcdocst1001
container.redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
container.redisPort: 6380
container.endpointEnabled: true
secretProviderClass.azure.keyvaultName: PRDFFCINFKV1001