environment: production
environmentCode: prd
appInsights.connectionString: REMOVED
container.messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
container.azureStorageAccountName: prdffcdocst1001
container.redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
container.redisPort: 6380
container.endpointEnabled: true