---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  azureStorageAccountName: prdffcdocst1001
  endpointEnabled: true
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret
      - objectName: prd-redisPassword
        objectType: secret

  secretObjects:
    - secretName: ffc-doc-statement-receiver
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appinsights-connectionString
          key: APPINSIGHTS_CONNECTION_STRING
        - objectName: prd-redisPassword
          key: REDIS_PASSWORD